/*
 * generated by Xtext 2.13.0
 */
package org.trimatek.digideal.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.trimatek.digideal.parser.antlr.internal.InternalContractParser;
import org.trimatek.digideal.services.ContractGrammarAccess;

public class ContractParser extends AbstractAntlrParser {

	@Inject
	private ContractGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalContractParser createParser(XtextTokenStream stream) {
		return new InternalContractParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Contract";
	}

	public ContractGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ContractGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
