/**
 * generated by Xtext 2.13.0
 */
package org.trimatek.digideal;

import org.trimatek.digideal.ContractStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ContractStandaloneSetup extends ContractStandaloneSetupGenerated {
  public static void doSetup() {
    new ContractStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
