/**
 * generated by Xtext 2.13.0
 */
package org.trimatek.digideal.contract;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.trimatek.digideal.contract.ContractFactory
 * @model kind="package"
 * @generated
 */
public interface ContractPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "contract";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.trimatek.org/digideal/Contract";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "contract";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ContractPackage eINSTANCE = org.trimatek.digideal.contract.impl.ContractPackageImpl.init();

  /**
   * The meta object id for the '{@link org.trimatek.digideal.contract.impl.ContractImpl <em>Contract</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.trimatek.digideal.contract.impl.ContractImpl
   * @see org.trimatek.digideal.contract.impl.ContractPackageImpl#getContract()
   * @generated
   */
  int CONTRACT = 0;

  /**
   * The feature id for the '<em><b>Cid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRACT__CID = 0;

  /**
   * The feature id for the '<em><b>Paragraph</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRACT__PARAGRAPH = 1;

  /**
   * The number of structural features of the '<em>Contract</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRACT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.trimatek.digideal.contract.impl.SentenceImpl <em>Sentence</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.trimatek.digideal.contract.impl.SentenceImpl
   * @see org.trimatek.digideal.contract.impl.ContractPackageImpl#getSentence()
   * @generated
   */
  int SENTENCE = 1;

  /**
   * The feature id for the '<em><b>Sentence Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENTENCE__SENTENCE_TYPE = 0;

  /**
   * The number of structural features of the '<em>Sentence</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENTENCE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.trimatek.digideal.contract.impl.SubjectImpl <em>Subject</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.trimatek.digideal.contract.impl.SubjectImpl
   * @see org.trimatek.digideal.contract.impl.ContractPackageImpl#getSubject()
   * @generated
   */
  int SUBJECT = 2;

  /**
   * The feature id for the '<em><b>Sentence Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBJECT__SENTENCE_TYPE = SENTENCE__SENTENCE_TYPE;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBJECT__NAME = SENTENCE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Address</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBJECT__ADDRESS = SENTENCE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Email</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBJECT__EMAIL = SENTENCE_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Subject</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBJECT_FEATURE_COUNT = SENTENCE_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.trimatek.digideal.contract.impl.ReferenceImpl <em>Reference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.trimatek.digideal.contract.impl.ReferenceImpl
   * @see org.trimatek.digideal.contract.impl.ContractPackageImpl#getReference()
   * @generated
   */
  int REFERENCE = 3;

  /**
   * The feature id for the '<em><b>Sentence Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE__SENTENCE_TYPE = SENTENCE__SENTENCE_TYPE;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE__TYPE = SENTENCE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Reference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE_FEATURE_COUNT = SENTENCE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.trimatek.digideal.contract.impl.PayToImpl <em>Pay To</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.trimatek.digideal.contract.impl.PayToImpl
   * @see org.trimatek.digideal.contract.impl.ContractPackageImpl#getPayTo()
   * @generated
   */
  int PAY_TO = 4;

  /**
   * The feature id for the '<em><b>Sentence Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAY_TO__SENTENCE_TYPE = SENTENCE__SENTENCE_TYPE;

  /**
   * The feature id for the '<em><b>Payer</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAY_TO__PAYER = SENTENCE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Collector</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAY_TO__COLLECTOR = SENTENCE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Sts</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAY_TO__STS = SENTENCE_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Pay To</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAY_TO_FEATURE_COUNT = SENTENCE_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.trimatek.digideal.contract.impl.PaymentConditionImpl <em>Payment Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.trimatek.digideal.contract.impl.PaymentConditionImpl
   * @see org.trimatek.digideal.contract.impl.ContractPackageImpl#getPaymentCondition()
   * @generated
   */
  int PAYMENT_CONDITION = 5;

  /**
   * The feature id for the '<em><b>Sentence Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAYMENT_CONDITION__SENTENCE_TYPE = SENTENCE__SENTENCE_TYPE;

  /**
   * The feature id for the '<em><b>Collector</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAYMENT_CONDITION__COLLECTOR = SENTENCE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAYMENT_CONDITION__DESCRIPTION = SENTENCE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Level</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAYMENT_CONDITION__LEVEL = SENTENCE_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Facts</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAYMENT_CONDITION__FACTS = SENTENCE_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Payment Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAYMENT_CONDITION_FEATURE_COUNT = SENTENCE_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.trimatek.digideal.contract.impl.FactsLevelImpl <em>Facts Level</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.trimatek.digideal.contract.impl.FactsLevelImpl
   * @see org.trimatek.digideal.contract.impl.ContractPackageImpl#getFactsLevel()
   * @generated
   */
  int FACTS_LEVEL = 6;

  /**
   * The feature id for the '<em><b>Options</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACTS_LEVEL__OPTIONS = 0;

  /**
   * The number of structural features of the '<em>Facts Level</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACTS_LEVEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.trimatek.digideal.contract.impl.AnyFactImpl <em>Any Fact</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.trimatek.digideal.contract.impl.AnyFactImpl
   * @see org.trimatek.digideal.contract.impl.ContractPackageImpl#getAnyFact()
   * @generated
   */
  int ANY_FACT = 7;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANY_FACT__VALUE = 0;

  /**
   * The number of structural features of the '<em>Any Fact</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANY_FACT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.trimatek.digideal.contract.impl.AllFactsImpl <em>All Facts</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.trimatek.digideal.contract.impl.AllFactsImpl
   * @see org.trimatek.digideal.contract.impl.ContractPackageImpl#getAllFacts()
   * @generated
   */
  int ALL_FACTS = 8;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALL_FACTS__VALUE = 0;

  /**
   * The number of structural features of the '<em>All Facts</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALL_FACTS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.trimatek.digideal.contract.impl.FactsImpl <em>Facts</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.trimatek.digideal.contract.impl.FactsImpl
   * @see org.trimatek.digideal.contract.impl.ContractPackageImpl#getFacts()
   * @generated
   */
  int FACTS = 9;

  /**
   * The feature id for the '<em><b>Fact</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACTS__FACT = 0;

  /**
   * The number of structural features of the '<em>Facts</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACTS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.trimatek.digideal.contract.impl.SupervisedByImpl <em>Supervised By</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.trimatek.digideal.contract.impl.SupervisedByImpl
   * @see org.trimatek.digideal.contract.impl.ContractPackageImpl#getSupervisedBy()
   * @generated
   */
  int SUPERVISED_BY = 10;

  /**
   * The feature id for the '<em><b>Sentence Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUPERVISED_BY__SENTENCE_TYPE = SENTENCE__SENTENCE_TYPE;

  /**
   * The feature id for the '<em><b>Agent</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUPERVISED_BY__AGENT = SENTENCE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Supervised By</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUPERVISED_BY_FEATURE_COUNT = SENTENCE_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.trimatek.digideal.contract.Contract <em>Contract</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Contract</em>'.
   * @see org.trimatek.digideal.contract.Contract
   * @generated
   */
  EClass getContract();

  /**
   * Returns the meta object for the attribute '{@link org.trimatek.digideal.contract.Contract#getCid <em>Cid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cid</em>'.
   * @see org.trimatek.digideal.contract.Contract#getCid()
   * @see #getContract()
   * @generated
   */
  EAttribute getContract_Cid();

  /**
   * Returns the meta object for the containment reference list '{@link org.trimatek.digideal.contract.Contract#getParagraph <em>Paragraph</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Paragraph</em>'.
   * @see org.trimatek.digideal.contract.Contract#getParagraph()
   * @see #getContract()
   * @generated
   */
  EReference getContract_Paragraph();

  /**
   * Returns the meta object for class '{@link org.trimatek.digideal.contract.Sentence <em>Sentence</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sentence</em>'.
   * @see org.trimatek.digideal.contract.Sentence
   * @generated
   */
  EClass getSentence();

  /**
   * Returns the meta object for the attribute '{@link org.trimatek.digideal.contract.Sentence#getSentenceType <em>Sentence Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sentence Type</em>'.
   * @see org.trimatek.digideal.contract.Sentence#getSentenceType()
   * @see #getSentence()
   * @generated
   */
  EAttribute getSentence_SentenceType();

  /**
   * Returns the meta object for class '{@link org.trimatek.digideal.contract.Subject <em>Subject</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Subject</em>'.
   * @see org.trimatek.digideal.contract.Subject
   * @generated
   */
  EClass getSubject();

  /**
   * Returns the meta object for the attribute '{@link org.trimatek.digideal.contract.Subject#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.trimatek.digideal.contract.Subject#getName()
   * @see #getSubject()
   * @generated
   */
  EAttribute getSubject_Name();

  /**
   * Returns the meta object for the attribute '{@link org.trimatek.digideal.contract.Subject#getAddress <em>Address</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Address</em>'.
   * @see org.trimatek.digideal.contract.Subject#getAddress()
   * @see #getSubject()
   * @generated
   */
  EAttribute getSubject_Address();

  /**
   * Returns the meta object for the attribute '{@link org.trimatek.digideal.contract.Subject#getEmail <em>Email</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Email</em>'.
   * @see org.trimatek.digideal.contract.Subject#getEmail()
   * @see #getSubject()
   * @generated
   */
  EAttribute getSubject_Email();

  /**
   * Returns the meta object for class '{@link org.trimatek.digideal.contract.Reference <em>Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Reference</em>'.
   * @see org.trimatek.digideal.contract.Reference
   * @generated
   */
  EClass getReference();

  /**
   * Returns the meta object for the reference '{@link org.trimatek.digideal.contract.Reference#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see org.trimatek.digideal.contract.Reference#getType()
   * @see #getReference()
   * @generated
   */
  EReference getReference_Type();

  /**
   * Returns the meta object for class '{@link org.trimatek.digideal.contract.PayTo <em>Pay To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pay To</em>'.
   * @see org.trimatek.digideal.contract.PayTo
   * @generated
   */
  EClass getPayTo();

  /**
   * Returns the meta object for the reference '{@link org.trimatek.digideal.contract.PayTo#getPayer <em>Payer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Payer</em>'.
   * @see org.trimatek.digideal.contract.PayTo#getPayer()
   * @see #getPayTo()
   * @generated
   */
  EReference getPayTo_Payer();

  /**
   * Returns the meta object for the reference '{@link org.trimatek.digideal.contract.PayTo#getCollector <em>Collector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Collector</em>'.
   * @see org.trimatek.digideal.contract.PayTo#getCollector()
   * @see #getPayTo()
   * @generated
   */
  EReference getPayTo_Collector();

  /**
   * Returns the meta object for the attribute '{@link org.trimatek.digideal.contract.PayTo#getSts <em>Sts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sts</em>'.
   * @see org.trimatek.digideal.contract.PayTo#getSts()
   * @see #getPayTo()
   * @generated
   */
  EAttribute getPayTo_Sts();

  /**
   * Returns the meta object for class '{@link org.trimatek.digideal.contract.PaymentCondition <em>Payment Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Payment Condition</em>'.
   * @see org.trimatek.digideal.contract.PaymentCondition
   * @generated
   */
  EClass getPaymentCondition();

  /**
   * Returns the meta object for the reference '{@link org.trimatek.digideal.contract.PaymentCondition#getCollector <em>Collector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Collector</em>'.
   * @see org.trimatek.digideal.contract.PaymentCondition#getCollector()
   * @see #getPaymentCondition()
   * @generated
   */
  EReference getPaymentCondition_Collector();

  /**
   * Returns the meta object for the attribute '{@link org.trimatek.digideal.contract.PaymentCondition#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.trimatek.digideal.contract.PaymentCondition#getDescription()
   * @see #getPaymentCondition()
   * @generated
   */
  EAttribute getPaymentCondition_Description();

  /**
   * Returns the meta object for the containment reference '{@link org.trimatek.digideal.contract.PaymentCondition#getLevel <em>Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Level</em>'.
   * @see org.trimatek.digideal.contract.PaymentCondition#getLevel()
   * @see #getPaymentCondition()
   * @generated
   */
  EReference getPaymentCondition_Level();

  /**
   * Returns the meta object for the containment reference '{@link org.trimatek.digideal.contract.PaymentCondition#getFacts <em>Facts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Facts</em>'.
   * @see org.trimatek.digideal.contract.PaymentCondition#getFacts()
   * @see #getPaymentCondition()
   * @generated
   */
  EReference getPaymentCondition_Facts();

  /**
   * Returns the meta object for class '{@link org.trimatek.digideal.contract.FactsLevel <em>Facts Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Facts Level</em>'.
   * @see org.trimatek.digideal.contract.FactsLevel
   * @generated
   */
  EClass getFactsLevel();

  /**
   * Returns the meta object for the containment reference '{@link org.trimatek.digideal.contract.FactsLevel#getOptions <em>Options</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Options</em>'.
   * @see org.trimatek.digideal.contract.FactsLevel#getOptions()
   * @see #getFactsLevel()
   * @generated
   */
  EReference getFactsLevel_Options();

  /**
   * Returns the meta object for class '{@link org.trimatek.digideal.contract.AnyFact <em>Any Fact</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Any Fact</em>'.
   * @see org.trimatek.digideal.contract.AnyFact
   * @generated
   */
  EClass getAnyFact();

  /**
   * Returns the meta object for the attribute '{@link org.trimatek.digideal.contract.AnyFact#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.trimatek.digideal.contract.AnyFact#getValue()
   * @see #getAnyFact()
   * @generated
   */
  EAttribute getAnyFact_Value();

  /**
   * Returns the meta object for class '{@link org.trimatek.digideal.contract.AllFacts <em>All Facts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>All Facts</em>'.
   * @see org.trimatek.digideal.contract.AllFacts
   * @generated
   */
  EClass getAllFacts();

  /**
   * Returns the meta object for the attribute '{@link org.trimatek.digideal.contract.AllFacts#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.trimatek.digideal.contract.AllFacts#getValue()
   * @see #getAllFacts()
   * @generated
   */
  EAttribute getAllFacts_Value();

  /**
   * Returns the meta object for class '{@link org.trimatek.digideal.contract.Facts <em>Facts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Facts</em>'.
   * @see org.trimatek.digideal.contract.Facts
   * @generated
   */
  EClass getFacts();

  /**
   * Returns the meta object for the attribute list '{@link org.trimatek.digideal.contract.Facts#getFact <em>Fact</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Fact</em>'.
   * @see org.trimatek.digideal.contract.Facts#getFact()
   * @see #getFacts()
   * @generated
   */
  EAttribute getFacts_Fact();

  /**
   * Returns the meta object for class '{@link org.trimatek.digideal.contract.SupervisedBy <em>Supervised By</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Supervised By</em>'.
   * @see org.trimatek.digideal.contract.SupervisedBy
   * @generated
   */
  EClass getSupervisedBy();

  /**
   * Returns the meta object for the containment reference '{@link org.trimatek.digideal.contract.SupervisedBy#getAgent <em>Agent</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Agent</em>'.
   * @see org.trimatek.digideal.contract.SupervisedBy#getAgent()
   * @see #getSupervisedBy()
   * @generated
   */
  EReference getSupervisedBy_Agent();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ContractFactory getContractFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.trimatek.digideal.contract.impl.ContractImpl <em>Contract</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.trimatek.digideal.contract.impl.ContractImpl
     * @see org.trimatek.digideal.contract.impl.ContractPackageImpl#getContract()
     * @generated
     */
    EClass CONTRACT = eINSTANCE.getContract();

    /**
     * The meta object literal for the '<em><b>Cid</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTRACT__CID = eINSTANCE.getContract_Cid();

    /**
     * The meta object literal for the '<em><b>Paragraph</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTRACT__PARAGRAPH = eINSTANCE.getContract_Paragraph();

    /**
     * The meta object literal for the '{@link org.trimatek.digideal.contract.impl.SentenceImpl <em>Sentence</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.trimatek.digideal.contract.impl.SentenceImpl
     * @see org.trimatek.digideal.contract.impl.ContractPackageImpl#getSentence()
     * @generated
     */
    EClass SENTENCE = eINSTANCE.getSentence();

    /**
     * The meta object literal for the '<em><b>Sentence Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENTENCE__SENTENCE_TYPE = eINSTANCE.getSentence_SentenceType();

    /**
     * The meta object literal for the '{@link org.trimatek.digideal.contract.impl.SubjectImpl <em>Subject</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.trimatek.digideal.contract.impl.SubjectImpl
     * @see org.trimatek.digideal.contract.impl.ContractPackageImpl#getSubject()
     * @generated
     */
    EClass SUBJECT = eINSTANCE.getSubject();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUBJECT__NAME = eINSTANCE.getSubject_Name();

    /**
     * The meta object literal for the '<em><b>Address</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUBJECT__ADDRESS = eINSTANCE.getSubject_Address();

    /**
     * The meta object literal for the '<em><b>Email</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUBJECT__EMAIL = eINSTANCE.getSubject_Email();

    /**
     * The meta object literal for the '{@link org.trimatek.digideal.contract.impl.ReferenceImpl <em>Reference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.trimatek.digideal.contract.impl.ReferenceImpl
     * @see org.trimatek.digideal.contract.impl.ContractPackageImpl#getReference()
     * @generated
     */
    EClass REFERENCE = eINSTANCE.getReference();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REFERENCE__TYPE = eINSTANCE.getReference_Type();

    /**
     * The meta object literal for the '{@link org.trimatek.digideal.contract.impl.PayToImpl <em>Pay To</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.trimatek.digideal.contract.impl.PayToImpl
     * @see org.trimatek.digideal.contract.impl.ContractPackageImpl#getPayTo()
     * @generated
     */
    EClass PAY_TO = eINSTANCE.getPayTo();

    /**
     * The meta object literal for the '<em><b>Payer</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PAY_TO__PAYER = eINSTANCE.getPayTo_Payer();

    /**
     * The meta object literal for the '<em><b>Collector</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PAY_TO__COLLECTOR = eINSTANCE.getPayTo_Collector();

    /**
     * The meta object literal for the '<em><b>Sts</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PAY_TO__STS = eINSTANCE.getPayTo_Sts();

    /**
     * The meta object literal for the '{@link org.trimatek.digideal.contract.impl.PaymentConditionImpl <em>Payment Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.trimatek.digideal.contract.impl.PaymentConditionImpl
     * @see org.trimatek.digideal.contract.impl.ContractPackageImpl#getPaymentCondition()
     * @generated
     */
    EClass PAYMENT_CONDITION = eINSTANCE.getPaymentCondition();

    /**
     * The meta object literal for the '<em><b>Collector</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PAYMENT_CONDITION__COLLECTOR = eINSTANCE.getPaymentCondition_Collector();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PAYMENT_CONDITION__DESCRIPTION = eINSTANCE.getPaymentCondition_Description();

    /**
     * The meta object literal for the '<em><b>Level</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PAYMENT_CONDITION__LEVEL = eINSTANCE.getPaymentCondition_Level();

    /**
     * The meta object literal for the '<em><b>Facts</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PAYMENT_CONDITION__FACTS = eINSTANCE.getPaymentCondition_Facts();

    /**
     * The meta object literal for the '{@link org.trimatek.digideal.contract.impl.FactsLevelImpl <em>Facts Level</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.trimatek.digideal.contract.impl.FactsLevelImpl
     * @see org.trimatek.digideal.contract.impl.ContractPackageImpl#getFactsLevel()
     * @generated
     */
    EClass FACTS_LEVEL = eINSTANCE.getFactsLevel();

    /**
     * The meta object literal for the '<em><b>Options</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FACTS_LEVEL__OPTIONS = eINSTANCE.getFactsLevel_Options();

    /**
     * The meta object literal for the '{@link org.trimatek.digideal.contract.impl.AnyFactImpl <em>Any Fact</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.trimatek.digideal.contract.impl.AnyFactImpl
     * @see org.trimatek.digideal.contract.impl.ContractPackageImpl#getAnyFact()
     * @generated
     */
    EClass ANY_FACT = eINSTANCE.getAnyFact();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ANY_FACT__VALUE = eINSTANCE.getAnyFact_Value();

    /**
     * The meta object literal for the '{@link org.trimatek.digideal.contract.impl.AllFactsImpl <em>All Facts</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.trimatek.digideal.contract.impl.AllFactsImpl
     * @see org.trimatek.digideal.contract.impl.ContractPackageImpl#getAllFacts()
     * @generated
     */
    EClass ALL_FACTS = eINSTANCE.getAllFacts();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALL_FACTS__VALUE = eINSTANCE.getAllFacts_Value();

    /**
     * The meta object literal for the '{@link org.trimatek.digideal.contract.impl.FactsImpl <em>Facts</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.trimatek.digideal.contract.impl.FactsImpl
     * @see org.trimatek.digideal.contract.impl.ContractPackageImpl#getFacts()
     * @generated
     */
    EClass FACTS = eINSTANCE.getFacts();

    /**
     * The meta object literal for the '<em><b>Fact</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FACTS__FACT = eINSTANCE.getFacts_Fact();

    /**
     * The meta object literal for the '{@link org.trimatek.digideal.contract.impl.SupervisedByImpl <em>Supervised By</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.trimatek.digideal.contract.impl.SupervisedByImpl
     * @see org.trimatek.digideal.contract.impl.ContractPackageImpl#getSupervisedBy()
     * @generated
     */
    EClass SUPERVISED_BY = eINSTANCE.getSupervisedBy();

    /**
     * The meta object literal for the '<em><b>Agent</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUPERVISED_BY__AGENT = eINSTANCE.getSupervisedBy_Agent();

  }

} //ContractPackage
