/**
 * generated by Xtext 2.13.0
 */
package org.trimatek.digideal.contract;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Contract</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.trimatek.digideal.contract.Contract#getCid <em>Cid</em>}</li>
 *   <li>{@link org.trimatek.digideal.contract.Contract#getParagraph <em>Paragraph</em>}</li>
 * </ul>
 *
 * @see org.trimatek.digideal.contract.ContractPackage#getContract()
 * @model
 * @generated
 */
public interface Contract extends EObject
{
  /**
   * Returns the value of the '<em><b>Cid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cid</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cid</em>' attribute.
   * @see #setCid(String)
   * @see org.trimatek.digideal.contract.ContractPackage#getContract_Cid()
   * @model
   * @generated
   */
  String getCid();

  /**
   * Sets the value of the '{@link org.trimatek.digideal.contract.Contract#getCid <em>Cid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cid</em>' attribute.
   * @see #getCid()
   * @generated
   */
  void setCid(String value);

  /**
   * Returns the value of the '<em><b>Paragraph</b></em>' containment reference list.
   * The list contents are of type {@link org.trimatek.digideal.contract.Sentence}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Paragraph</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Paragraph</em>' containment reference list.
   * @see org.trimatek.digideal.contract.ContractPackage#getContract_Paragraph()
   * @model containment="true"
   * @generated
   */
  EList<Sentence> getParagraph();

} // Contract
