/**
 * generated by Xtext 2.13.0
 */
package org.trimatek.digideal.contract;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Facts</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.trimatek.digideal.contract.Facts#getFact <em>Fact</em>}</li>
 * </ul>
 *
 * @see org.trimatek.digideal.contract.ContractPackage#getFacts()
 * @model
 * @generated
 */
public interface Facts extends EObject
{
  /**
   * Returns the value of the '<em><b>Fact</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fact</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fact</em>' attribute list.
   * @see org.trimatek.digideal.contract.ContractPackage#getFacts_Fact()
   * @model unique="false"
   * @generated
   */
  EList<String> getFact();

} // Facts
