/**
 * generated by Xtext 2.13.0
 */
package org.trimatek.digideal.contract;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Facts Level</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.trimatek.digideal.contract.FactsLevel#getOptions <em>Options</em>}</li>
 * </ul>
 *
 * @see org.trimatek.digideal.contract.ContractPackage#getFactsLevel()
 * @model
 * @generated
 */
public interface FactsLevel extends EObject
{
  /**
   * Returns the value of the '<em><b>Options</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Options</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Options</em>' containment reference.
   * @see #setOptions(EObject)
   * @see org.trimatek.digideal.contract.ContractPackage#getFactsLevel_Options()
   * @model containment="true"
   * @generated
   */
  EObject getOptions();

  /**
   * Sets the value of the '{@link org.trimatek.digideal.contract.FactsLevel#getOptions <em>Options</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Options</em>' containment reference.
   * @see #getOptions()
   * @generated
   */
  void setOptions(EObject value);

} // FactsLevel
