/**
 * generated by Xtext 2.13.0
 */
package org.trimatek.digideal.contract;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.trimatek.digideal.contract.Reference#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.trimatek.digideal.contract.ContractPackage#getReference()
 * @model
 * @generated
 */
public interface Reference extends Sentence
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(Subject)
   * @see org.trimatek.digideal.contract.ContractPackage#getReference_Type()
   * @model
   * @generated
   */
  Subject getType();

  /**
   * Sets the value of the '{@link org.trimatek.digideal.contract.Reference#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(Subject value);

} // Reference
