/**
 * generated by Xtext 2.13.0
 */
package org.trimatek.digideal.contract;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Supervised By</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.trimatek.digideal.contract.SupervisedBy#getAgent <em>Agent</em>}</li>
 * </ul>
 *
 * @see org.trimatek.digideal.contract.ContractPackage#getSupervisedBy()
 * @model
 * @generated
 */
public interface SupervisedBy extends Sentence
{
  /**
   * Returns the value of the '<em><b>Agent</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Agent</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Agent</em>' containment reference.
   * @see #setAgent(Subject)
   * @see org.trimatek.digideal.contract.ContractPackage#getSupervisedBy_Agent()
   * @model containment="true"
   * @generated
   */
  Subject getAgent();

  /**
   * Sets the value of the '{@link org.trimatek.digideal.contract.SupervisedBy#getAgent <em>Agent</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Agent</em>' containment reference.
   * @see #getAgent()
   * @generated
   */
  void setAgent(Subject value);

} // SupervisedBy
