/*
 * generated by Xtext 2.13.0
 */
package org.trimatek.digideal.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class ContractWebModule extends AbstractContractWebModule {
}
