/**
 * generated by Xtext 2.13.0
 */
package org.trimatek.digideal.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.trimatek.digideal.ContractRuntimeModule;
import org.trimatek.digideal.ContractStandaloneSetup;
import org.trimatek.digideal.ide.ContractIdeModule;
import org.trimatek.digideal.web.ContractWebModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class ContractWebSetup extends ContractStandaloneSetup {
  @Override
  public Injector createInjector() {
    ContractRuntimeModule _contractRuntimeModule = new ContractRuntimeModule();
    ContractIdeModule _contractIdeModule = new ContractIdeModule();
    ContractWebModule _contractWebModule = new ContractWebModule();
    return Guice.createInjector(Modules2.mixin(_contractRuntimeModule, _contractIdeModule, _contractWebModule));
  }
}
