/**
 * generated by Xtext 2.13.0
 */
package org.trimatek.digideal.web;

import org.trimatek.digideal.web.AbstractContractWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class ContractWebModule extends AbstractContractWebModule {
}
