/**
 * generated by Xtext 2.13.0
 */
package org.trimatek.digideal.validation;

import org.trimatek.digideal.validation.AbstractContractValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ContractValidator extends AbstractContractValidator {
}
