/*
 * generated by Xtext 2.13.0
 */
package org.trimatek.digideal


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ContractStandaloneSetup extends ContractStandaloneSetupGenerated {

	def static void doSetup() {
		new ContractStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
