/*
 * generated by Xtext 2.13.0
 */
package org.trimatek.digideal.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link ContractWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractContractWebModule extends DefaultWebModule {

}
