/**
 * generated by Xtext 2.13.0
 */
package org.trimatek.digideal.scoping;

import org.trimatek.digideal.scoping.AbstractContractScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class ContractScopeProvider extends AbstractContractScopeProvider {
}
