/**
 * generated by Xtext 2.13.0
 */
package org.trimatek.digideal.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.trimatek.digideal.ContractRuntimeModule;
import org.trimatek.digideal.ContractStandaloneSetup;
import org.trimatek.digideal.ide.ContractIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class ContractIdeSetup extends ContractStandaloneSetup {
  @Override
  public Injector createInjector() {
    ContractRuntimeModule _contractRuntimeModule = new ContractRuntimeModule();
    ContractIdeModule _contractIdeModule = new ContractIdeModule();
    return Guice.createInjector(Modules2.mixin(_contractRuntimeModule, _contractIdeModule));
  }
}
