/**
 * generated by Xtext 2.13.0
 */
package org.trimatek.digideal.ide;

import org.trimatek.digideal.ide.AbstractContractIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ContractIdeModule extends AbstractContractIdeModule {
}
